-- ============================================================
--  daily_planner.sql — Database setup for My Daily Planner
--  Run this file in phpMyAdmin or MySQL CLI to create the
--  database, users table, and seed the default admin account.
-- ============================================================

CREATE DATABASE IF NOT EXISTS daily_planner
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE daily_planner;

CREATE TABLE IF NOT EXISTS users (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    reg_no      VARCHAR(50)   NOT NULL UNIQUE,
    password    VARCHAR(255)  NOT NULL,
    branch      VARCHAR(20)   NOT NULL,
    semester    VARCHAR(10)   DEFAULT '7th',
    grp         VARCHAR(5)    NOT NULL,
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    last_login  TIMESTAMP     NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed default admin account
-- Password: admin123  (bcrypt hash generated by PHP password_hash)
INSERT INTO users (name, reg_no, password, branch, grp)
VALUES (
    'Administrator',
    'admin',
    '$2y$10$ka0vrs4IkeiMWAJmJUHE4uAZ/2Kt3ipkWapzUmVKpTb3VpX94wSba',
    'ADMIN',
    '1'
) ON DUPLICATE KEY UPDATE name = name;
