-- ============================================================
--  daily_planner.sql — Database setup for My Daily Planner
--
--  [FOR LOCAL XAMPP]:
--  Import this entire file into phpMyAdmin or MySQL CLI.
--
--  [FOR INFINITYFREE]:
--  1. Open phpMyAdmin from your InfinityFree control panel.
--  2. Click on your database (if0_42656834_tat_sangam).
--  3. Click "SQL" tab and run the CREATE TABLE & INSERT below.
-- ============================================================

CREATE DATABASE IF NOT EXISTS tat_sangam
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE tat_sangam;

CREATE TABLE IF NOT EXISTS users (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    reg_no      VARCHAR(50)   NOT NULL UNIQUE,
    password    VARCHAR(255)  NOT NULL,
    branch      VARCHAR(20)   NOT NULL,
    semester    VARCHAR(10)   DEFAULT '7th',
    grp         VARCHAR(5)    NOT NULL,
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    last_login  TIMESTAMP     NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed default admin account
-- Password: admin123  (bcrypt hash generated by PHP password_hash)
INSERT INTO users (name, reg_no, password, branch, grp)
VALUES (
    'Administrator',
    'admin',
    '$2y$10$ka0vrs4IkeiMWAJmJUHE4uAZ/2Kt3ipkWapzUmVKpTb3VpX94wSba',
    'ADMIN',
    '1'
) ON DUPLICATE KEY UPDATE name = name;
